# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10LV72yv_293lPnH784R_4dH7XP3Are2Q
"""

# Sentiment Analysis on Product Reviews
# Muhammad Ahmad
# BS Information Technology - University of Sargodha

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix




import kagglehub
import os

# download amazon fine food reviews dataset from kaggle
path = kagglehub.dataset_download("snap/amazon-fine-food-reviews")
print("Path to dataset files:", path)

# load the csv file
csv_file = os.path.join(path, "Reviews.csv")
df_raw = pd.read_csv(csv_file)

print("Total reviews loaded:", len(df_raw))
print(df_raw.head())

# the Score column has ratings from 1 to 5
# we convert scores to sentiment labels:
# 4 and 5 stars = positive (1)
# 3 stars = neutral (0)
# 1 and 2 stars = negative (-1)

def score_to_sentiment(score):
    if score >= 4:
        return 1
    elif score == 3:
        return 0
    else:
        return -1

df_raw['sentiment'] = df_raw['Score'].apply(score_to_sentiment)

# use only the Text column and sentiment column
# also take a sample of 10000 rows so it runs faster
df = df_raw[['Text', 'sentiment']].copy()
df.columns = ['review', 'sentiment']
df = df.sample(10000, random_state=42).reset_index(drop=True)

print("\nSentiment counts:")
print(df['sentiment'].value_counts())

# 1 = positive, 0 = neutral, -1 = negative
labels = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1,
]

df = pd.DataFrame({'review': reviews, 'sentiment': labels})

print("Dataset shape:", df.shape)
print("\nFirst few rows:")
print(df.head())

print("\nSentiment counts:")
print(df['sentiment'].value_counts())


# plot 1 - sentiment distribution
plt.figure(figsize=(6, 4))
counts = df['sentiment'].value_counts().sort_index()
plt.bar(['Negative (-1)', 'Neutral (0)', 'Positive (1)'],
        [counts.get(-1, 0), counts.get(0, 0), counts.get(1, 0)],
        color=['red', 'gray', 'green'])
plt.title('Sentiment Distribution in Dataset')
plt.ylabel('Number of Reviews')
plt.tight_layout()
plt.show()


# text cleaning
# remove punctuation and numbers, make lowercase
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = text.strip()
    return text

df['cleaned'] = df['review'].apply(clean_text)

print("\nCleaned text sample:")
print(df[['review', 'cleaned']].head(3))


# remove stopwords manually
# stopwords are small common words that dont help the model learn sentiment
# for example "the", "is", "i", "and" dont tell us if review is good or bad
stop_words = ['i', 'me', 'my', 'the', 'a', 'an', 'is', 'it', 'its',
              'this', 'that', 'and', 'or', 'but', 'in', 'on', 'at',
              'to', 'for', 'of', 'with', 'am', 'are', 'was', 'were',
              'be', 'been', 'have', 'has', 'had', 'do', 'does', 'did',
              'will', 'would', 'could', 'should', 'so', 'if', 'as',
              'what', 'which', 'who', 'from', 'by', 'about', 'just']

def remove_stopwords(text):
    words = text.split()
    filtered = [w for w in words if w not in stop_words]
    return ' '.join(filtered)

df['cleaned'] = df['cleaned'].apply(remove_stopwords)

print("\nAfter removing stopwords:")
print(df['cleaned'].head(5))


# TF-IDF vectorization
# this turns text into numbers
# each word gets a score based on how important it is in the review
# common words across all reviews get low score, unique important words get high score

tfidf = TfidfVectorizer(max_features=300)
X = tfidf.fit_transform(df['cleaned'])
y = df['sentiment']

print("\nTF-IDF matrix shape:", X.shape)


# train test split - 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training size:", X_train.shape[0])
print("Testing size:", X_test.shape[0])


# model 1 - logistic regression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

acc_lr = accuracy_score(y_test, pred_lr)
print("\nLogistic Regression:")
print("Accuracy:", round(acc_lr, 4))
print(classification_report(y_test, pred_lr, target_names=['Negative', 'Neutral', 'Positive']))


# model 2 - naive bayes
# this is a simple probability based model
# it works well for text and is fast to train
nb = MultinomialNB()
nb.fit(X_train, y_train)
pred_nb = nb.predict(X_test)

acc_nb = accuracy_score(y_test, pred_nb)
print("Naive Bayes:")
print("Accuracy:", round(acc_nb, 4))
print(classification_report(y_test, pred_nb, target_names=['Negative', 'Neutral', 'Positive']))


# model 3 - SVM
# support vector machine usually gives best results for text classification
svm = LinearSVC(max_iter=1000)
svm.fit(X_train, y_train)
pred_svm = svm.predict(X_test)

acc_svm = accuracy_score(y_test, pred_svm)
print("SVM:")
print("Accuracy:", round(acc_svm, 4))
print(classification_report(y_test, pred_svm, target_names=['Negative', 'Neutral', 'Positive']))


# compare all 3 models
comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Naive Bayes', 'SVM'],
    'Accuracy': [round(acc_lr, 4), round(acc_nb, 4), round(acc_svm, 4)]
})
print("\nAll Models Comparison:")
print(comparison)


# plot 2 - accuracy comparison bar chart
plt.figure(figsize=(7, 4))
colors = ['steelblue', 'orange', 'green']
bars = plt.bar(comparison['Model'], comparison['Accuracy'], color=colors)
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy Score')
plt.ylim(0, 1.2)
for bar, val in zip(bars, comparison['Accuracy']):
    plt.text(bar.get_x() + bar.get_width()/2, val + 0.02,
             str(val), ha='center', fontsize=10)
plt.tight_layout()
plt.show()


# plot 3 - confusion matrix for logistic regression
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, pred_lr)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Negative', 'Neutral', 'Positive'],
            yticklabels=['Negative', 'Neutral', 'Positive'])
plt.title('Confusion Matrix - Logistic Regression')
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.tight_layout()
plt.show()

# confusion matrix tells us where the model makes mistakes
# for example if it predicted neutral when actual was positive that shows in the matrix


# testing on new reviews i wrote myself
# just to see if the model can predict sentiment on unseen text
new_reviews = [
    "i really love this product amazing quality",
    "very bad product broke after two days",
    "its okay nothing special average product"
]

new_cleaned = [remove_stopwords(clean_text(r)) for r in new_reviews]
new_tfidf = tfidf.transform(new_cleaned)
new_pred = lr.predict(new_tfidf)

print("\nTesting on new reviews:")
for review, pred in zip(new_reviews, new_pred):
    if pred == 1:
        label = "Positive"
    elif pred == -1:
        label = "Negative"
    else:
        label = "Neutral"
    print("Review:", review)
    print("Predicted:", label)
    print()